'use client';

import React, { useRef, useState } from 'react';
import {
  FileText,
  Printer,
  Download,
  Share2,
  CheckCircle2,
  ShieldCheck,
  TrendingUp,
  Coins,
  Building2,
  Users,
  Activity,
  Layers,
  Sparkles,
} from 'lucide-react';
import CompanyLogo from '@/components/common/CompanyLogo';
import { BLOOMBERG_VALUATION_PROFILES } from './BloombergFairValueCompass';

interface ResearchMemoModalProps {
  isOpen: boolean;
  onClose: () => void;
  symbol: string;
}

export default function BloombergResearchMemoModal({
  isOpen,
  onClose,
  symbol = 'BMRI',
}: ResearchMemoModalProps) {
  const [copied, setCopied] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const data = BLOOMBERG_VALUATION_PROFILES[symbol] || BLOOMBERG_VALUATION_PROFILES['BMRI'];

  const handlePrint = () => {
    window.print();
  };

  const handleCopySummary = () => {
    const text = `[RESEARCH MEMO BLOOMBERG AGY] ${data.symbol} - ${data.name}
Harga Pasar: Rp ${data.marketPrice.toLocaleString('id-ID')}
Fair Value Konsensus: Rp ${data.consensusFairValue.toLocaleString('id-ID')} (+${data.upsidePotential.toFixed(1)}% Upside)
Status Valuasi: ${data.valuationBand}
Model DCF: Rp ${data.dcfFairValue.toLocaleString('id-ID')}
Model Graham: Rp ${data.grahamNumber.toLocaleString('id-ID')}
Dividen DPS: Rp ${data.dps} (Yield: ${( (data.dps / data.marketPrice) * 100 ).toFixed(2)}%)
Katalis: ${data.catalysts.join('; ')}
Generated by Antigravity Bloomberg Terminal IDX`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="relative w-full max-w-3xl rounded-2xl border border-zinc-700 bg-zinc-950 p-6 shadow-2xl space-y-6 font-mono text-zinc-200 my-8">
        {/* Header Action Bar */}
        <div className="flex items-center justify-between pb-4 border-b border-zinc-800">
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-lg bg-amber-500/20 text-amber-400 border border-amber-500/30">
              <FileText className="w-5 h-5" />
            </span>
            <div>
              <h3 className="text-base font-bold text-white tracking-wide">
                EQUITY RESEARCH MEMO &bull; BLOOMBERG &lt;ANR&gt;
              </h3>
              <p className="text-[11px] text-zinc-400">Institutional One-Page Investment Thesis & Model Breakdown</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopySummary}
              className="px-3 py-1.5 rounded-lg text-xs font-bold bg-zinc-800 border border-zinc-700 hover:text-white flex items-center gap-1.5 cursor-pointer"
            >
              <Share2 className="w-3.5 h-3.5" />
              <span>{copied ? 'Tersalin!' : 'Salin Teks'}</span>
            </button>
            <button
              type="button"
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg text-xs font-bold bg-amber-500 text-black hover:bg-amber-400 flex items-center gap-1.5 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Cetak / Simpan PDF</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-800 transition-colors"
            >
              &times;
            </button>
          </div>
        </div>

        {/* Printable Memo Content */}
        <div ref={printRef} className="space-y-5 text-xs">
          {/* Company Title Box */}
          <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900/60 flex items-start justify-between">
            <div className="flex items-center gap-3">
              <CompanyLogo symbol={data.symbol} name={data.name} size={48} rounded="lg" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold text-white">{data.symbol}</span>
                  <span className="text-xs px-2 py-0.5 rounded font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                    BUY / OVERWEIGHT
                  </span>
                </div>
                <div className="text-zinc-400 text-xs">{data.name} &bull; {data.sector}</div>
              </div>
            </div>

            <div className="text-right">
              <div className="text-[10px] text-zinc-400 uppercase">Fair Value Target</div>
              <div className="text-xl font-bold text-amber-400 font-mono-num">
                Rp {data.consensusFairValue.toLocaleString('id-ID')}
              </div>
              <div className="text-[11px] text-emerald-400 font-bold">
                +{data.upsidePotential.toFixed(1)}% Upside Margin
              </div>
            </div>
          </div>

          {/* Key Multi-Valuation Matrix Table */}
          <div>
            <div className="text-xs font-bold text-white uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <Layers className="w-4 h-4 text-amber-400" />
              <span>1. Multi-Valuation Methodology Matrix:</span>
            </div>
            <table className="w-full text-xs border border-zinc-800 rounded-lg overflow-hidden">
              <thead className="bg-zinc-900 text-zinc-400 text-[11px]">
                <tr>
                  <th className="text-left p-2.5">Metodologi Valuasi</th>
                  <th className="text-left p-2.5">Parameter Inti</th>
                  <th className="text-right p-2.5">Nilai Wajar</th>
                  <th className="text-right p-2.5">Diskon vs Pasar</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800 bg-zinc-900/30">
                <tr>
                  <td className="p-2.5 font-bold text-white">Discounted Cash Flow (DCF)</td>
                  <td className="p-2.5 text-zinc-400">WACC {data.wacc}%, Terminal Growth {data.terminalGrowth}%</td>
                  <td className="p-2.5 text-right font-mono-num font-bold text-white">Rp {data.dcfFairValue.toLocaleString('id-ID')}</td>
                  <td className="p-2.5 text-right font-mono-num text-emerald-400 font-bold">+{( ((data.dcfFairValue - data.marketPrice) / data.marketPrice) * 100 ).toFixed(1)}%</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold text-white">Benjamin Graham Formula</td>
                  <td className="p-2.5 text-zinc-400">&radic;(22.5 &times; EPS {data.epsLTM} &times; BVPS {data.bvps})</td>
                  <td className="p-2.5 text-right font-mono-num font-bold text-white">Rp {data.grahamNumber.toLocaleString('id-ID')}</td>
                  <td className="p-2.5 text-right font-mono-num text-emerald-400 font-bold">+{( ((data.grahamNumber - data.marketPrice) / data.marketPrice) * 100 ).toFixed(1)}%</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold text-white">Gordon Dividend Model (DDM)</td>
                  <td className="p-2.5 text-zinc-400">DPS Rp {data.dps}, Dividend Yield {( (data.dps / data.marketPrice) * 100 ).toFixed(2)}%</td>
                  <td className="p-2.5 text-right font-mono-num font-bold text-white">Rp {data.ddmGordonValue.toLocaleString('id-ID')}</td>
                  <td className="p-2.5 text-right font-mono-num text-emerald-400 font-bold">+{( ((data.ddmGordonValue - data.marketPrice) / data.marketPrice) * 100 ).toFixed(1)}%</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold text-white">Historical PBV Band 3Y</td>
                  <td className="p-2.5 text-zinc-400">Mean Multiple {data.pbvMean3Y}x &bull; ROE {data.roe}%</td>
                  <td className="p-2.5 text-right font-mono-num font-bold text-white">Rp {data.pbvHistoricalValue.toLocaleString('id-ID')}</td>
                  <td className="p-2.5 text-right font-mono-num text-emerald-400 font-bold">+{( ((data.pbvHistoricalValue - data.marketPrice) / data.marketPrice) * 100 ).toFixed(1)}%</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Investment Catalysts & Thesis */}
          <div className="p-3.5 rounded-xl border border-zinc-800 bg-zinc-900/50 space-y-2">
            <div className="font-bold text-white uppercase text-[11px] flex items-center gap-1.5">
              <Sparkles className="w-4 h-4 text-amber-400" />
              <span>2. Investment Thesis & Key Catalysts:</span>
            </div>
            <ul className="list-disc list-inside space-y-1 text-zinc-300 leading-relaxed">
              {data.catalysts.map((c, i) => (
                <li key={i}>{c}</li>
              ))}
            </ul>
          </div>

          {/* Disclaimer Footer */}
          <div className="pt-3 border-t border-zinc-800 text-[10px] text-zinc-500 flex justify-between">
            <span>Terminal Bloomberg Research &bull; Antigravity Agentic Engine</span>
            <span>Waktu Terbit: 02 Oktober 2026 &bull; BEI Jakarta</span>
          </div>
        </div>
      </div>
    </div>
  );
}
